//ALERTS:
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const USER_LOADED_ERROR = "USER_LOADED_ERROR";
