//ALERTS:
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_LOADED_ERROR = "USER_LOADED_ERROR";
export const START_LOGIN_LOADING = "START_LOGIN_LOADING";
export const START_REGISTER_LOADING = "START_REGISTER_LOADING";
export const LOGOUT = "LOGOUT";
export const AUTH_GENERAL_ERROR = "AUTH_GENERAL_ERROR";
export const RESET_PASSWORD_LINK_SENT = "RESET_PASSWORD_LINK_SENT";
